### ISSUE TITLE
It should be possible to explicit name images and containers

### ISSUE THREAD

**Issue by vidarl** [docker/fig#541]
I am aware of ongoing discussion about "The project name should be configurable", https://github.com/docker/fig/issues/45"

However, I think it should be easy to simply name and tag images and containers explicitly, like this:
```
ubuntu:
  build: dockerfiles/ubuntu
  image_name: nickname/ubuntu:latest
web:
  image: nickname/ubuntu:latest
  image_name: nickname/apache:2.4
  container_name:web
```
