### ISSUE TITLE
Proposal: Allow multiple command entries

### ISSUE THREAD

**Issue by gone** [docker/fig#816]
I'm running a django server via fig for local development. I'd like to integrate a command line driven proxy server that handles live reloads (browser-sync). 
Current solution is run the fig cluster, then locally open a new terminal and run browser-sync start --proxy localhost:8000, and then navigate to the url that browser-sync gives me (localhost:3000). 
What I'd really like to do is have fig handle this proxy redirect internally by mapping a single url and runing two TTY's within the web instance.

I prose supporting this syntax in the fig.yml:

db:
  image: mdillon/postgis:9.3
web:
  environment:
    DATABASE_URL: postgis://postgres:postgres@localhost:5432/myproject
    DJANGO_SETTINGS_MODULE: myproject.settings.local
  build: .
  command:
    - python manage.py runserver 0.0.0.0:8001
    - browser-sync start --port 8000 --proxy localhost:8001
  volumes:
    - .:/code
  ports:
    - "8000:8000"
  links:
    - db

I'd be happy to work on a patch if it seems like a good idea

**Comment by dnephin** [comment]
Docker only supports a single command (https://docs.docker.com/reference/builder/#cmd) so I'm not sure how this would work.

Do you want two different containers?

**Comment by gone** [comment]
I didn't realize this was a docker constraint - I assumed fig was spinning up a shell within the docker container to run the command in. Two containers might work, I'll try

**Comment by gone** [comment]
```
db:
  image: mdillon/postgis:9.3
web:
  environment:
    DATABASE_URL: postgis://postgres:postgres@localhost:5432/myproject
    DJANGO_SETTINGS_MODULE: myproject.settings.local
  build: .
  command: python manage.py runserver 0.0.0.0:8001
  volumes:
    - .:/code
  ports:
    - "8001:8001"
  links:
    - db
livereload:
  build: ./livereload
  command: browser-sync start --port 8000 --proxy web:8001 --files="/code/static_source/sass/*.sass,/code/templates/*.html"
  volumes:
    - .:/code
  links:
    - web
  ports:
    - "8000:8000"
```
